name: Bug report
description: Create a report to help us improve
labels: ["🐛Bug", "Triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      value: |
          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error
  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: markdown
    attributes:
      value: Please complete the following information:
  - type: input
    id: version_and_build
    attributes:
      label: Version
      placeholder: see bottom of the browser screen
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. Windows, Linux, OS X
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g. Chrome, Safari, Firefox, ...
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
